# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QFrame,
    QHBoxLayout, QHeaderView, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPlainTextEdit,
    QPushButton, QSizePolicy, QStatusBar, QTreeWidget,
    QTreeWidgetItem, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1200, 800)
        self.a_preferences = QAction(MainWindow)
        self.a_preferences.setObjectName(u"a_preferences")
        self.a_preferences.setEnabled(True)
        self.a_preferences.setText(u"Preferences...")
        self.a_preferences.setIconText(u"Preferences...")
#if QT_CONFIG(tooltip)
        self.a_preferences.setToolTip(u"Preferences...")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.a_preferences.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.a_preferences.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.a_version = QAction(MainWindow)
        self.a_version.setObjectName(u"a_version")
        self.a_exit = QAction(MainWindow)
        self.a_exit.setObjectName(u"a_exit")
        self.a_logout = QAction(MainWindow)
        self.a_logout.setObjectName(u"a_logout")
        self.a_updates_check = QAction(MainWindow)
        self.a_updates_check.setObjectName(u"a_updates_check")
        self.w_central = QWidget(MainWindow)
        self.w_central.setObjectName(u"w_central")
        self.w_central.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.w_central.sizePolicy().hasHeightForWidth())
        self.w_central.setSizePolicy(sizePolicy)
#if QT_CONFIG(tooltip)
        self.w_central.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.w_central.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.w_central.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.w_central.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.w_central.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.horizontalLayout = QHBoxLayout(self.w_central)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.lv_list_user = QVBoxLayout()
        self.lv_list_user.setObjectName(u"lv_list_user")
        self.tr_lists_user = QTreeWidget(self.w_central)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(2, u"Info");
        __qtreewidgetitem.setText(0, u"Name");
        self.tr_lists_user.setHeaderItem(__qtreewidgetitem)
        __qtreewidgetitem1 = QTreeWidgetItem(self.tr_lists_user)
        __qtreewidgetitem1.setFlags(Qt.ItemIsEnabled);
        __qtreewidgetitem2 = QTreeWidgetItem(self.tr_lists_user)
        __qtreewidgetitem2.setFlags(Qt.ItemIsEnabled);
        __qtreewidgetitem3 = QTreeWidgetItem(self.tr_lists_user)
        __qtreewidgetitem3.setFlags(Qt.ItemIsEnabled);
        self.tr_lists_user.setObjectName(u"tr_lists_user")
#if QT_CONFIG(tooltip)
        self.tr_lists_user.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tr_lists_user.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.tr_lists_user.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.tr_lists_user.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.tr_lists_user.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.tr_lists_user.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tr_lists_user.setProperty("showDropIndicator", False)
        self.tr_lists_user.setIndentation(10)
        self.tr_lists_user.setUniformRowHeights(True)
        self.tr_lists_user.setSortingEnabled(True)
        self.tr_lists_user.header().setCascadingSectionResizes(True)
        self.tr_lists_user.header().setHighlightSections(True)
        self.tr_lists_user.header().setProperty("showSortIndicator", True)

        self.lv_list_user.addWidget(self.tr_lists_user)

        self.lv_list_control = QHBoxLayout()
        self.lv_list_control.setObjectName(u"lv_list_control")
        self.pb_reload_user_lists = QPushButton(self.w_central)
        self.pb_reload_user_lists.setObjectName(u"pb_reload_user_lists")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pb_reload_user_lists.sizePolicy().hasHeightForWidth())
        self.pb_reload_user_lists.setSizePolicy(sizePolicy1)

        self.lv_list_control.addWidget(self.pb_reload_user_lists)

        self.pb_download_list = QPushButton(self.w_central)
        self.pb_download_list.setObjectName(u"pb_download_list")
        sizePolicy1.setHeightForWidth(self.pb_download_list.sizePolicy().hasHeightForWidth())
        self.pb_download_list.setSizePolicy(sizePolicy1)

        self.lv_list_control.addWidget(self.pb_download_list)


        self.lv_list_user.addLayout(self.lv_list_control)


        self.horizontalLayout.addLayout(self.lv_list_user)

        self.lv_search_result = QVBoxLayout()
#ifndef Q_OS_MAC
        self.lv_search_result.setSpacing(-1)
#endif
        self.lv_search_result.setObjectName(u"lv_search_result")
        self.lh_search = QHBoxLayout()
        self.lh_search.setObjectName(u"lh_search")
        self.l_search = QLineEdit(self.w_central)
        self.l_search.setObjectName(u"l_search")
        self.l_search.setAcceptDrops(False)
#if QT_CONFIG(tooltip)
        self.l_search.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.l_search.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.l_search.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.l_search.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.l_search.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.l_search.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.l_search.setText(u"")
        self.l_search.setPlaceholderText(u"Type and press ENTER to search...")
        self.l_search.setClearButtonEnabled(True)

        self.lh_search.addWidget(self.l_search)

        self.cb_search_type = QComboBox(self.w_central)
        self.cb_search_type.setObjectName(u"cb_search_type")
#if QT_CONFIG(tooltip)
        self.cb_search_type.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.cb_search_type.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.cb_search_type.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.cb_search_type.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.cb_search_type.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.cb_search_type.setCurrentText(u"")
        self.cb_search_type.setPlaceholderText(u"")

        self.lh_search.addWidget(self.cb_search_type)

        self.pb_search = QPushButton(self.w_central)
        self.pb_search.setObjectName(u"pb_search")
#if QT_CONFIG(statustip)
        self.pb_search.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.pb_search.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.pb_search.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.pb_search.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.pb_search.setText(u"Search")
#if QT_CONFIG(shortcut)
        self.pb_search.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.lh_search.addWidget(self.pb_search)


        self.lv_search_result.addLayout(self.lh_search)

        self.tr_results = QTreeWidget(self.w_central)
        self.tr_results.setObjectName(u"tr_results")
        self.tr_results.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tr_results.setProperty("showDropIndicator", False)
        self.tr_results.setDragDropOverwriteMode(False)
        self.tr_results.setAlternatingRowColors(False)
        self.tr_results.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.tr_results.setIndentation(10)
        self.tr_results.setSortingEnabled(True)
        self.tr_results.header().setProperty("showSortIndicator", True)
        self.tr_results.header().setStretchLastSection(False)

        self.lv_search_result.addWidget(self.tr_results)

        self.lh_download = QHBoxLayout()
        self.lh_download.setObjectName(u"lh_download")
        self.l_quality_audio = QLabel(self.w_central)
        self.l_quality_audio.setObjectName(u"l_quality_audio")
#if QT_CONFIG(tooltip)
        self.l_quality_audio.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.l_quality_audio.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.l_quality_audio.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.l_quality_audio.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.l_quality_audio.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.l_quality_audio.setText(u"Audio")
        self.l_quality_audio.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.lh_download.addWidget(self.l_quality_audio)

        self.cb_quality_audio = QComboBox(self.w_central)
        self.cb_quality_audio.setObjectName(u"cb_quality_audio")
#if QT_CONFIG(tooltip)
        self.cb_quality_audio.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.cb_quality_audio.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.cb_quality_audio.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.cb_quality_audio.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.cb_quality_audio.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.cb_quality_audio.setCurrentText(u"")
        self.cb_quality_audio.setPlaceholderText(u"")
        self.cb_quality_audio.setFrame(True)

        self.lh_download.addWidget(self.cb_quality_audio)

        self.l_quality_video = QLabel(self.w_central)
        self.l_quality_video.setObjectName(u"l_quality_video")
#if QT_CONFIG(tooltip)
        self.l_quality_video.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.l_quality_video.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.l_quality_video.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.l_quality_video.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.l_quality_video.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.l_quality_video.setText(u"Video")
        self.l_quality_video.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.lh_download.addWidget(self.l_quality_video)

        self.cb_quality_video = QComboBox(self.w_central)
        self.cb_quality_video.setObjectName(u"cb_quality_video")
#if QT_CONFIG(tooltip)
        self.cb_quality_video.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.cb_quality_video.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.cb_quality_video.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.cb_quality_video.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.cb_quality_video.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.cb_quality_video.setCurrentText(u"")
        self.cb_quality_video.setPlaceholderText(u"")

        self.lh_download.addWidget(self.cb_quality_video)

        self.pb_download = QPushButton(self.w_central)
        self.pb_download.setObjectName(u"pb_download")
#if QT_CONFIG(tooltip)
        self.pb_download.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pb_download.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.pb_download.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.pb_download.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.pb_download.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.pb_download.setText(u"Download")
#if QT_CONFIG(shortcut)
        self.pb_download.setShortcut(u"")
#endif // QT_CONFIG(shortcut)

        self.lh_download.addWidget(self.pb_download)

        self.lh_download.setStretch(0, 5)
        self.lh_download.setStretch(2, 5)
        self.lh_download.setStretch(4, 15)

        self.lv_search_result.addLayout(self.lh_download)

        self.te_debug = QPlainTextEdit(self.w_central)
        self.te_debug.setObjectName(u"te_debug")
        self.te_debug.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Maximum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.te_debug.sizePolicy().hasHeightForWidth())
        self.te_debug.setSizePolicy(sizePolicy2)
        self.te_debug.setMaximumSize(QSize(16777215, 16777215))
        self.te_debug.setAcceptDrops(False)
#if QT_CONFIG(tooltip)
        self.te_debug.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.te_debug.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.te_debug.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.te_debug.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.te_debug.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.te_debug.setUndoRedoEnabled(False)
        self.te_debug.setReadOnly(True)

        self.lv_search_result.addWidget(self.te_debug)


        self.horizontalLayout.addLayout(self.lv_search_result)

        self.lv_info = QVBoxLayout()
        self.lv_info.setObjectName(u"lv_info")
        self.lv_info_item = QVBoxLayout()
        self.lv_info_item.setObjectName(u"lv_info_item")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.l_pm_cover = QLabel(self.w_central)
        self.l_pm_cover.setObjectName(u"l_pm_cover")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.l_pm_cover.sizePolicy().hasHeightForWidth())
        self.l_pm_cover.setSizePolicy(sizePolicy3)
        self.l_pm_cover.setMaximumSize(QSize(280, 280))
        self.l_pm_cover.setBaseSize(QSize(0, 0))
        self.l_pm_cover.setFrameShape(QFrame.NoFrame)
        self.l_pm_cover.setPixmap(QPixmap(u"default_album_image.png"))
        self.l_pm_cover.setScaledContents(True)
        self.l_pm_cover.setAlignment(Qt.AlignHCenter|Qt.AlignTop)

        self.horizontalLayout_2.addWidget(self.l_pm_cover)


        self.lv_info_item.addLayout(self.horizontalLayout_2)


        self.lv_info.addLayout(self.lv_info_item)

        self.lv_queue_download = QVBoxLayout()
        self.lv_queue_download.setObjectName(u"lv_queue_download")
        self.l_h_queue_download = QLabel(self.w_central)
        self.l_h_queue_download.setObjectName(u"l_h_queue_download")
        font = QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        self.l_h_queue_download.setFont(font)

        self.lv_queue_download.addWidget(self.l_h_queue_download)

        self.tr_queue_download = QTreeWidget(self.w_central)
        self.tr_queue_download.setObjectName(u"tr_queue_download")
        self.tr_queue_download.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tr_queue_download.setTabKeyNavigation(False)
        self.tr_queue_download.setProperty("showDropIndicator", False)
        self.tr_queue_download.setDragDropOverwriteMode(False)
        self.tr_queue_download.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.tr_queue_download.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tr_queue_download.setRootIsDecorated(False)
        self.tr_queue_download.setItemsExpandable(False)
        self.tr_queue_download.setSortingEnabled(False)
        self.tr_queue_download.setExpandsOnDoubleClick(False)
        self.tr_queue_download.header().setProperty("showSortIndicator", False)
        self.tr_queue_download.header().setStretchLastSection(False)

        self.lv_queue_download.addWidget(self.tr_queue_download)

        self.pb_queue_download_item_remove = QPushButton(self.w_central)
        self.pb_queue_download_item_remove.setObjectName(u"pb_queue_download_item_remove")
        self.pb_queue_download_item_remove.setEnabled(False)

        self.lv_queue_download.addWidget(self.pb_queue_download_item_remove)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.pb_clear_finished = QPushButton(self.w_central)
        self.pb_clear_finished.setObjectName(u"pb_clear_finished")

        self.horizontalLayout_3.addWidget(self.pb_clear_finished)

        self.pb_clear_all = QPushButton(self.w_central)
        self.pb_clear_all.setObjectName(u"pb_clear_all")

        self.horizontalLayout_3.addWidget(self.pb_clear_all)


        self.lv_queue_download.addLayout(self.horizontalLayout_3)


        self.lv_info.addLayout(self.lv_queue_download)


        self.horizontalLayout.addLayout(self.lv_info)

        self.horizontalLayout.setStretch(1, 50)
        self.horizontalLayout.setStretch(2, 25)
        MainWindow.setCentralWidget(self.w_central)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1200, 24))
#if QT_CONFIG(tooltip)
        self.menubar.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.menubar.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.menubar.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.menubar.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.menubar.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.m_file = QMenu(self.menubar)
        self.m_file.setObjectName(u"m_file")
#if QT_CONFIG(tooltip)
        self.m_file.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.m_file.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.m_file.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.m_file.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.m_file.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.m_help = QMenu(self.menubar)
        self.m_help.setObjectName(u"m_help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
#if QT_CONFIG(tooltip)
        self.statusbar.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.statusbar.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.statusbar.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.statusbar.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.statusbar.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.statusbar.setLayoutDirection(Qt.LeftToRight)
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.m_file.menuAction())
        self.menubar.addAction(self.m_help.menuAction())
        self.m_file.addAction(self.a_preferences)
        self.m_file.addAction(self.a_logout)
        self.m_file.addAction(self.a_exit)
        self.m_help.addAction(self.a_version)
        self.m_help.addAction(self.a_updates_check)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.a_version.setText(QCoreApplication.translate("MainWindow", u"Version", None))
        self.a_exit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.a_logout.setText(QCoreApplication.translate("MainWindow", u"Logout", None))
        self.a_updates_check.setText(QCoreApplication.translate("MainWindow", u"Check for Updates", None))
        ___qtreewidgetitem = self.tr_lists_user.headerItem()
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("MainWindow", u"obj", None));

        __sortingEnabled = self.tr_lists_user.isSortingEnabled()
        self.tr_lists_user.setSortingEnabled(False)
        ___qtreewidgetitem1 = self.tr_lists_user.topLevelItem(0)
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("MainWindow", u"Playlists", None));
        ___qtreewidgetitem2 = self.tr_lists_user.topLevelItem(1)
        ___qtreewidgetitem2.setText(0, QCoreApplication.translate("MainWindow", u"Mixes", None));
        ___qtreewidgetitem3 = self.tr_lists_user.topLevelItem(2)
        ___qtreewidgetitem3.setText(0, QCoreApplication.translate("MainWindow", u"Favorites", None));
        self.tr_lists_user.setSortingEnabled(__sortingEnabled)

        self.pb_reload_user_lists.setText(QCoreApplication.translate("MainWindow", u"Reload", None))
        self.pb_download_list.setText(QCoreApplication.translate("MainWindow", u"Download List", None))
        ___qtreewidgetitem4 = self.tr_results.headerItem()
        ___qtreewidgetitem4.setText(6, QCoreApplication.translate("MainWindow", u"Quality", None));
        ___qtreewidgetitem4.setText(5, QCoreApplication.translate("MainWindow", u"Duration", None));
        ___qtreewidgetitem4.setText(4, QCoreApplication.translate("MainWindow", u"Album", None));
        ___qtreewidgetitem4.setText(3, QCoreApplication.translate("MainWindow", u"Title", None));
        ___qtreewidgetitem4.setText(2, QCoreApplication.translate("MainWindow", u"Artist", None));
        ___qtreewidgetitem4.setText(1, QCoreApplication.translate("MainWindow", u"obj", None));
        ___qtreewidgetitem4.setText(0, QCoreApplication.translate("MainWindow", u"#", None));
        self.te_debug.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Logs...", None))
        self.l_pm_cover.setText("")
        self.l_h_queue_download.setText(QCoreApplication.translate("MainWindow", u"Download Queue", None))
        ___qtreewidgetitem5 = self.tr_queue_download.headerItem()
        ___qtreewidgetitem5.setText(4, QCoreApplication.translate("MainWindow", u"Quality", None));
        ___qtreewidgetitem5.setText(3, QCoreApplication.translate("MainWindow", u"Type", None));
        ___qtreewidgetitem5.setText(2, QCoreApplication.translate("MainWindow", u"Name", None));
        ___qtreewidgetitem5.setText(1, QCoreApplication.translate("MainWindow", u"obj", None));
        ___qtreewidgetitem5.setText(0, QCoreApplication.translate("MainWindow", u"\ud83e\uddd1\u200d\ud83d\udcbb\ufe0f", None));
        self.pb_queue_download_item_remove.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.pb_clear_finished.setText(QCoreApplication.translate("MainWindow", u"Clear Finished", None))
        self.pb_clear_all.setText(QCoreApplication.translate("MainWindow", u"Clear All", None))
        self.m_file.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.m_help.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

